
package AplikasiObjekWisata;

import Connection.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Destinasi extends javax.swing.JFrame {

    /**
     * Creates new form Destinasi
     */
    public Destinasi() {
        initComponents();
         tampilan();
        clear();}
    
    public final Connection conn = new Koneksi().getConnection();
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    DefaultTableModel tabMode;
    
    
    public void tampilan(){
        Object [] baris = {"id_destinasi", "nama_destinasi", "fasilitas","harga"};
        tabMode = new DefaultTableModel(null, baris);
        Tbldestinasi.setModel(tabMode);
        try {
                String sql = "SELECT * FROM destinasi";
                st = conn.createStatement();
                rs = st.executeQuery(sql);
                while (rs.next()){
                        String id = rs.getString("id_destinasi");
                        String nd = rs.getString("nm_destinasi");
                        String f = rs.getString("fasilitas");
                        String h = rs.getString("harga");

                        Object [] data = {id,nd,f,h};
                        tabMode.addRow(data);
                }
        } catch (Exception e){
                System.out.println(e.toString());
        }
    }
    
    public void clear(){
        Iddestinasi.setText(null);
        Nmdestinasi.setText(null);
        Fasilitas.setText(null);
        Harga.setText(null);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Iddestinasi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nmdestinasi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Fasilitas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        Btnsimpan = new javax.swing.JButton();
        Btnedit = new javax.swing.JButton();
        Btnhapus = new javax.swing.JButton();
        Btnkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbldestinasi = new javax.swing.JTable();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DESTINASI WISATA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("ID DESTINASI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 20));

        Iddestinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IddestinasiActionPerformed(evt);
            }
        });
        jPanel1.add(Iddestinasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("NAMA DESTINASI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 20));

        Nmdestinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NmdestinasiActionPerformed(evt);
            }
        });
        jPanel1.add(Nmdestinasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 180, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("FASILITAS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 20));

        Fasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FasilitasActionPerformed(evt);
            }
        });
        jPanel1.add(Fasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("HARGA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 20));

        Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaActionPerformed(evt);
            }
        });
        jPanel1.add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 180, 30));

        Btnsimpan.setText("SIMPAN");
        Btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(Btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        Btnedit.setText("EDIT");
        Btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtneditActionPerformed(evt);
            }
        });
        jPanel1.add(Btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        Btnhapus.setText("HAPUS");
        Btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(Btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        Btnkeluar.setText("KELUAR");
        Btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(Btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        Tbldestinasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tbldestinasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID DESTINASI", "NAMA DESTINASI", "FASILITAS", "HARGA"
            }
        ));
        Tbldestinasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbldestinasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbldestinasi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 420, 230));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Bgg.jpg"))); // NOI18N
        jPanel1.add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IddestinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IddestinasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IddestinasiActionPerformed

    private void NmdestinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NmdestinasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NmdestinasiActionPerformed

    private void FasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FasilitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FasilitasActionPerformed

    private void HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaActionPerformed

    private void BtnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsimpanActionPerformed
             if (Iddestinasi.getText().equals("") || 
                     Nmdestinasi.getText().equals("") ||  
                     Fasilitas.getText().equals("") || 
                     Harga.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Field Tidak Boleh Kosong");
        } else {
            try {
               int s;
               String sql = "INSERT INTO destinasi VALUES ('"+Iddestinasi.getText()+"',"
                       + " '"+Nmdestinasi.getText()+"',"
                       + " '"+Fasilitas.getText()+"',"
                       + " '"+Harga.getText()+"')";
               st = conn.createStatement();
               s = st.executeUpdate(sql);
               if (s == 1){
                   JOptionPane.showMessageDialog(null, "Sukses");
                   clear();
                   tampilan();
               }
           } catch (Exception e){
                   System.out.println(e.toString());
           } 
       }
    }//GEN-LAST:event_BtnsimpanActionPerformed

    private void BtneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtneditActionPerformed
 int c = JOptionPane.showConfirmDialog(null, "Ingin Mengubah Data?","Informasi", JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.YES_OPTION){
            if (Iddestinasi.getText().equals("") || 
                    Nmdestinasi.getText().equals("") ||  
                    Fasilitas.getText().equals("") || 
                    Harga.getText().equals("") ){
                JOptionPane.showMessageDialog(null, "Field Tidak Boleh Kosong");
            } else {
                try {
                    int s;
                    String sql = "UPDATE destinasi SET nm_destinasi = '"
                            +Nmdestinasi.getText()+"',"
                            + " fasilitas = '"+Fasilitas.getText()+"', "
                            + "harga = '"+Harga.getText()
                            +"' WHERE id_destinasi = '"
                            +Iddestinasi.getText()+"' ";
                    st = conn.createStatement();
                    s = st.executeUpdate(sql);
                    if (s == 1){
                        JOptionPane.showMessageDialog(null, "Sukses");
                        clear();
                        tampilan();
                    }
                } catch (Exception e){
                        System.out.println(e.toString());
                } 
            }
        }
    }//GEN-LAST:event_BtneditActionPerformed

    private void BtnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnhapusActionPerformed
        int c = JOptionPane.showConfirmDialog(null, "Ingin Menghapus Data?","Informasi", JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.YES_OPTION){
            try {
                int s;
                String sql = "DELETE FROM destinasi WHERE Id_destinasi = '"+Iddestinasi.getText()+"' ";
                st = conn.createStatement();
                s = st.executeUpdate(sql);
                if (s == 1){
                    JOptionPane.showMessageDialog(null, "Sukses");
                    clear();
                    tampilan();
                }
            } catch (Exception e){
                    System.out.println(e.toString());
            } 
        }  
    }//GEN-LAST:event_BtnhapusActionPerformed

    private void BtnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnkeluarActionPerformed
    new MenuUtama().setVisible(true);
         dispose(); 
    }//GEN-LAST:event_BtnkeluarActionPerformed

    private void TbldestinasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbldestinasiMouseClicked
        int baris = Tbldestinasi.getSelectedRow();
	Iddestinasi.setText(Tbldestinasi.getValueAt(baris, 0).toString());
	Nmdestinasi.setText(Tbldestinasi.getValueAt(baris, 1).toString());
        Fasilitas.setText(Tbldestinasi.getValueAt(baris, 2).toString());
        Harga.setText(Tbldestinasi.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_TbldestinasiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Destinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Destinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Destinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Destinasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Destinasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JButton Btnedit;
    private javax.swing.JButton Btnhapus;
    private javax.swing.JButton Btnkeluar;
    private javax.swing.JButton Btnsimpan;
    private javax.swing.JTextField Fasilitas;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField Iddestinasi;
    private javax.swing.JTextField Nmdestinasi;
    private javax.swing.JTable Tbldestinasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
