/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiObjekWisata;

/**
 *
 * @author Acer
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btnlogout = new javax.swing.JButton();
        Btnpelanggan = new javax.swing.JButton();
        Btnpemesanan = new javax.swing.JButton();
        Btndestinasi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("MENU UTAMA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        Btnlogout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Btnlogout.setText("LOGOUT");
        Btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(Btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        Btnpelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/BtnPelanggan-removebg-preview.png"))); // NOI18N
        Btnpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpelangganActionPerformed(evt);
            }
        });
        jPanel1.add(Btnpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 60, 70));

        Btnpemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/BtnTransaksi.png"))); // NOI18N
        Btnpemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpemesananActionPerformed(evt);
            }
        });
        jPanel1.add(Btnpemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 70, 70));

        Btndestinasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/BtnDestinasi.png"))); // NOI18N
        Btndestinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndestinasiActionPerformed(evt);
            }
        });
        jPanel1.add(Btndestinasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, 64));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("PELANGGAN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("PEMESANAN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("DESTINASI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/BgMenuUtama.jpg"))); // NOI18N
        jPanel1.add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtndestinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndestinasiActionPerformed
    new Destinasi().setVisible(true);
    dispose();
    }//GEN-LAST:event_BtndestinasiActionPerformed

    private void BtnpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpelangganActionPerformed
    new Pelanggan().setVisible(true);
    dispose();
    }//GEN-LAST:event_BtnpelangganActionPerformed

    private void BtnpemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpemesananActionPerformed
    new Pemesanan().setVisible(true);
    dispose();
    }//GEN-LAST:event_BtnpemesananActionPerformed

    private void BtnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnlogoutActionPerformed
    new Login().setVisible(true);
    dispose();
    javax.swing.JOptionPane.showMessageDialog(null,"ANDA BERHASIL LOGOUT");
    }//GEN-LAST:event_BtnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JButton Btndestinasi;
    private javax.swing.JButton Btnlogout;
    private javax.swing.JButton Btnpelanggan;
    private javax.swing.JButton Btnpemesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
